package com.example.project1.dao;

import com.example.project1.pojo.MallOrder;
import com.example.project1.pojo.MallOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    long countByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int deleteByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int insert(MallOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int insertSelective(MallOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    List<MallOrder> selectByExample(MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    MallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallOrder row, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int updateByExample(@Param("row") MallOrder row, @Param("example") MallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int updateByPrimaryKeySelective(MallOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order
     *
     * @mbg.generated Wed Mar 29 17:02:31 CST 2023
     */
    int updateByPrimaryKey(MallOrder row);

    List<MallOrder> selectByUID(Integer uID);

    MallOrder selectByOrderNo(Long orderNo);
}