package com.example.project1.dao;

import com.example.project1.pojo.MallOrderItem;
import com.example.project1.pojo.MallOrderItemExample;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

public interface MallOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    long countByExample(MallOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int deleteByExample(MallOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int insert(MallOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int insertSelective(MallOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    List<MallOrderItem> selectByExample(MallOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    MallOrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallOrderItem row, @Param("example") MallOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int updateByExample(@Param("row") MallOrderItem row, @Param("example") MallOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int updateByPrimaryKeySelective(MallOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_order_item
     *
     * @mbg.generated Wed Mar 29 17:23:03 CST 2023
     */
    int updateByPrimaryKey(MallOrderItem row);

    int batchInsertSelective(List<MallOrderItem> orderItemList);

    List<MallOrderItem> selectByOrderNoSet(Set<Long> orderNoSet);

    List<MallOrderItem> selectByOrderNo(Long orderNo);
}