package com.example.project1.dao;

import com.example.project1.pojo.MallCart;
import com.example.project1.pojo.MallCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    long countByExample(MallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int deleteByExample(MallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int insert(MallCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int insertSelective(MallCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    List<MallCart> selectByExample(MallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    MallCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallCart row, @Param("example") MallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int updateByExample(@Param("row") MallCart row, @Param("example") MallCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int updateByPrimaryKeySelective(MallCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_cart
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    int updateByPrimaryKey(MallCart row);

    List<MallCart> selectByUserId(Integer userId);

    MallCart selectUserIdWithProductId(Integer userId, Integer productId);

    int deleteByProductId(Integer productId);

    int deleteByProductIdAndUserID(@Param("userId") Integer userId, @Param("productId") Integer productId);
}