package com.example.project1.dao;

import com.example.project1.pojo.MallProduct;
import com.example.project1.pojo.MallProductExample;
import com.example.project1.pojo.MallProductWithBLOBs;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

public interface MallProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    long countByExample(MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int deleteByExample(MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int insert(MallProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int insertSelective(MallProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    List<MallProductWithBLOBs> selectByExampleWithBLOBs(MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    List<MallProduct> selectByExample(MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    MallProductWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallProductWithBLOBs row, @Param("example") MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") MallProductWithBLOBs row, @Param("example") MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByExample(@Param("row") MallProduct row, @Param("example") MallProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByPrimaryKeySelective(MallProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(MallProductWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_product
     *
     * @mbg.generated Fri Mar 24 20:35:30 CST 2023
     */
    int updateByPrimaryKey(MallProduct row);

    List<MallProduct> selectByIdSet(Set<Integer> subCategoryId);

    List<MallProduct> selectByProductIdSet(HashSet<Integer> productIDset);
}