package com.example.project1.dao;

import com.example.project1.pojo.MallShipping;
import com.example.project1.pojo.MallShippingExample;
import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

public interface MallShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    long countByExample(MallShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int deleteByExample(MallShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int insert(MallShipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int insertSelective(MallShipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    List<MallShipping> selectByExample(MallShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    MallShipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallShipping row, @Param("example") MallShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int updateByExample(@Param("row") MallShipping row, @Param("example") MallShippingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int updateByPrimaryKeySelective(MallShipping row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_shipping
     *
     * @mbg.generated Mon Mar 27 16:29:33 CST 2023
     */
    int updateByPrimaryKey(MallShipping row);

    int deleteByPrimaryKeyAndUserId(@Param("id") Integer id, @Param("userId") Integer userId);

    List<MallShipping> selectByUserId(Integer userId);

    MallShipping selectByPrimaryKeyAndUserId(@Param("userId") Integer userId, @Param("id") Integer id);

    List<MallShipping> selectByIdSet(Set<Integer> shippingIdSet);
}