package com.example.project1.dao;

import com.example.project1.pojo.MallCategory;
import com.example.project1.pojo.MallCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    long countByExample(MallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int deleteByExample(MallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int insert(MallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int insertSelective(MallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    List<MallCategory> selectByExample(MallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    MallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int updateByExampleSelective(@Param("row") MallCategory row, @Param("example") MallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int updateByExample(@Param("row") MallCategory row, @Param("example") MallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int updateByPrimaryKeySelective(MallCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_category
     *
     * @mbg.generated Thu Mar 23 18:11:24 CST 2023
     */
    int updateByPrimaryKey(MallCategory row);

    List<MallCategory> selectAllActive();

}