package com.example.project1.pojo;

import java.util.Date;

public class MallCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.user_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.product_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.count
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.create_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.update_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mall_cart.selected
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    private Boolean selected;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.id
     *
     * @return the value of mall_cart.id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.id
     *
     * @param id the value for mall_cart.id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.user_id
     *
     * @return the value of mall_cart.user_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.user_id
     *
     * @param userId the value for mall_cart.user_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.product_id
     *
     * @return the value of mall_cart.product_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.product_id
     *
     * @param productId the value for mall_cart.product_id
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.count
     *
     * @return the value of mall_cart.count
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.count
     *
     * @param count the value for mall_cart.count
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.create_time
     *
     * @return the value of mall_cart.create_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.create_time
     *
     * @param createTime the value for mall_cart.create_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.update_time
     *
     * @return the value of mall_cart.update_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.update_time
     *
     * @param updateTime the value for mall_cart.update_time
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mall_cart.selected
     *
     * @return the value of mall_cart.selected
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public Boolean getSelected() {
        return selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mall_cart.selected
     *
     * @param selected the value for mall_cart.selected
     *
     * @mbg.generated Mon Mar 27 16:25:09 CST 2023
     */
    public void setSelected(Boolean selected) {
        this.selected = selected;
    }
}